In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
my_w = pd.read_csv('/kaggle/input/my-tr-data/new_test_data.csv')

In [ ]:
!pip install  scikit-learn  xgboost pandas dagshub mlflow

In [ ]:
import dagshub
dagshub.init(repo_owner='kechik21',repo_name='ML_HW1',mlflow=True)

In [ ]:
import mlflow
model_xgb = mlflow.pyfunc.load_model("Models:/MyModel/1")

In [ ]:
my_sub = model_xgb.predict(my_w)

In [ ]:
my_sub = pd.DataFrame({
    'Id': range(1461, 1461+len(my_sub)),
    'SalePrice': my_sub})

In [17]:
my_sub.to_csv('/kaggle/working/Sumbission.csv', index=False)

In [18]:
my_sub.head(10)

     Id      SalePrice
0  1461  119098.164062
1  1462  162084.531250
2  1463  191742.125000
3  1464  197833.890625
4  1465  184432.984375
5  1466  165389.953125
6  1467  181394.281250
7  1468  164378.718750
8  1469  185759.656250
9  1470  120807.351562